export default [
    {
        id: '1',
        name: 'Just Breathe :)',
        uri: require('../assets/sounds/breathe.wav'),
        soundFile: 'breathe.wav',
        category: 'Healing',
        keywords: ['breathe', 'breath', 'breathing'],
    },
    {
        id: '2',
        name: 'Brush your Teeth',
        uri: require('../assets/sounds/brush_teeth.wav'),
        soundFile: 'brush_teeth.wav',
        category: 'Detailing',
        keywords: ['brush', 'teeth', 'toothbrush'],
    },
    {
        id: '3',
        name: 'Coffee Break',
        uri: require('../assets/sounds/caffiene_check.wav'),
        soundFile: 'caffiene_check.wav',
        category: 'Healing',
        keywords: ['coffee', 'caffiene', 'espresso'],
    },
    {
        id: '4',
        name: 'Call your Father',
        uri: require('../assets/sounds/call_your_father.wav'),
        soundFile: 'call_your_father.wav',
        category: 'Family',
        keywords: ['father', 'dad', 'papa'],
    },
    {
        id: '5',
        name: 'Call your Mother',
        uri: require('../assets/sounds/call_your_mom.wav'),
        soundFile: 'call_your_mom.wav',
        category: 'Family',
        keywords: ['mother', 'mom', 'mama'],
    },
    {
        id: '6',
        name: 'Clean',
        uri: require('../assets/sounds/clean.wav'),
        soundFile: 'clean.wav',
        category: 'Cleaning',
        keywords: ['clean', 'cleaning', 'dust', 'vacuum', 'mop', 'sweep'],
    },
    {
        id: '7',
        name: 'Dog Alert',
        uri: require('../assets/sounds/dogbark.wav'),
        soundFile: 'dogbark.wav',
        category: 'Family',
        keywords: ['dog', 'bark', 'doggo'],
    },
    {
        id: '8',
        name: 'Fooooooooood',
        uri: require('../assets/sounds/eat.wav'),
        soundFile: 'eat.wav',
        category: 'Healing',
        keywords: ['food', 'eat', 'dinner', 'lunch', 'breakfast'],
    },
    {
        id: '9',
        name: 'Screen Break (for the eyes)',
        uri: require('../assets/sounds/look_away_from_screen.wav'),
        soundFile: 'look_away_from_screen.wav',
        category: 'Healing',
        keywords: ['screen', 'break'],
    },
    {
        id: '10',
        name: 'Posture Check',
        uri: require('../assets/sounds/posture_check.wav'),
        soundFile: 'posture_check.wav',
        category: 'Healing',
        keywords: ['posture'],
    },
    {
        id: '11',
        name: 'Relax',
        uri: require('../assets/sounds/relax.wav'),
        soundFile: 'relax.wav',
        category: 'Healing',
        keywords: ['relax'],
    },
    {
        id: '12',
        name: 'Roll your Shoulders',
        uri: require('../assets/sounds/roll_your_shoulders.wav'),
        soundFile: 'roll_your_shoulders.wav',
        category: 'Healing',
        keywords: ['shoulders'],
    },
    {
        id: '13',
        name: 'Take a Walk!',
        uri: require('../assets/sounds/short_walk.wav'),
        soundFile: 'short_walk.wav',
        category: 'Healing',
        keywords: ['walk', 'walking'],
    },
    {
        id: '14',
        name: 'Stretch',
        uri: require('../assets/sounds/stretch.wav'),
        soundFile: 'stretch.wav',
        category: 'Healing',
        keywords: ['stretch', 'stretching'],
    },
    {
        id: '15',
        name: 'Drink Water',
        uri: require('../assets/sounds/water.wav'),
        soundFile: 'water.wav',
        category: 'Healing',
        keywords: ['water'],
    },
    {
        id: '16',
        name: 'Write Something Down',
        uri: require('../assets/sounds/write_down_one_thought.wav'),
        soundFile: 'write_down_one_thought.wav',
        category: 'Wisdom',
        keywords: ['write'],
    },
    {
        id: '17',
        name: 'Cat Stuff',
        uri: require('../assets/sounds/catmeow.wav'),
        soundFile: 'catmeow.wav',
        category: 'Family',
        keywords: ['cat'],
    },
    // Add more sounds here as needed
];
